
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  recommendation:
    build:
      context: .
      dockerfile: model/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./model:/app
    environment:
      - FLASK_APP=recommendation_service.py
      - FLASK_ENV=development
