services:
  app:
    depends_on:
      - recommendation
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  recommendation:
    build:
      context: ./recommendation_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./recommendation_service:/app
    environment:
      - FLASK_APP=recommendation_service.py
      - FLASK_ENV=development

  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"

  testing:
    depends_on:
      - app
      - selenium
    build:
      context: ./robot_tests
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    # volumes:
      # - ./robot_tests:/app
    environment:
      - FLASK_APP=first_page_tests.robot
      - FLASK_ENV=development
