services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  recommendation:
    build:
      context: ./recommendation_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./recommendation_service:/app
    environment:
      - FLASK_APP=recommendation_service.py
      - FLASK_ENV=development
